# Generated by Django 4.1.5 on 2023-01-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('slug', models.SlugField()),
                ('post', models.TextField()),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app1.usermodel')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
