# Generated by Django 4.1.5 on 2023-01-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0002_contentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='post',
            new_name='body',
        ),
    ]
