# Generated by Django 4.1.5 on 2023-01-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0004_remove_contentmodel_author_webpagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='body',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app1.webpagemodel'),
        ),
    ]
