# Generated by Django 4.1.5 on 2023-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0006_alter_contentmodel_body_alter_contentmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagemodel',
            name='background_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
