# Generated by Django 4.1.5 on 2023-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0007_alter_webpagemodel_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
