# Generated by Django 4.1.5 on 2023-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0008_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagemodel',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
