# Generated by Django 4.1.5 on 2023-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0009_alter_webpagemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
