# Generated by Django 4.1.5 on 2023-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0013_likemodel_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
