# Generated by Django 4.1.5 on 2023-03-10 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0014_alter_contentmodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
