# Generated by Django 4.1.5 on 2023-03-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0015_commentmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='slug',
        ),
    ]
